steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/line-zoom-bot-kun-notifier:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/line-zoom-bot-kun-notifier:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'line-zoom-bot-kun-notifier', '--image', 'gcr.io/$PROJECT_ID/line-zoom-bot-kun-notifier:$COMMIT_SHA', '--region', 'asia-northeast1']
images:
  - gcr.io/$PROJECT_ID/line-zoom-bot-kun-notifier:$COMMIT_SHA
